export const SET_PAGINATION_LINKS = 'SET_PAGINATION_LINKS';
export const SET_NAVIGATION = 'SET_NAVIGATION';
export const SET_RESULTS = 'SET_RESULTS';
export const SET_APPLIED_SELECTION = 'SET_APPLIED_SELECTION';
export const SET_PARAMS = 'SET_PARAMS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const SETTINGS = 'SETTINGS';
