module.exports = {
    "rules": {
        // base javascript overrides that conflict with react environment
        "new-cap": 0,
        "no-invalid-this": 0,
        // react plugin rules
        "react/default-props-match-prop-types": 2,
        "react/display-name": [2, {"ignoreTranspilerName": false}],
        "react/forbid-component-props": 0,
        "react/forbid-elements": 0,
        "react/forbid-foreign-prop-types": 2,
        "react/forbid-prop-types": 0,
        "react/jsx-boolean-value": [2, "always"],
        "react/jsx-closing-bracket-location": [2, {"nonEmpty": "line-aligned", "selfClosing": "line-aligned"}],
        "react/jsx-closing-tag-location": 0,
        "react/jsx-curly-spacing": [2, "never"],
        "react/jsx-equals-spacing": [2, "never"],
        "react/jsx-filename-extension": 0,
        "react/jsx-first-prop-new-line": [2, "multiline"],
        "react/jsx-handler-names": 0,
        "react/jsx-indent-props": [2, 4],
        "react/jsx-indent": [2, 4],
        "react/jsx-key": 0,
        "react/jsx-max-props-per-line": [2, {"maximum": 1}],
        "react/jsx-no-bind": [2, {"allowBind": true}],
        "react/jsx-no-comment-textnodes": 2,
        "react/jsx-no-duplicate-props": 2,
        "react/jsx-no-literals": 2,
        "react/jsx-no-undef": 2,
        "react/jsx-no-target-blank": 2,
        "react/jsx-pascal-case": 2,
        "react/jsx-sort-props": 2,
        "react/jsx-tag-spacing": [2, {"closingSlash": "never", "beforeSelfClosing": "never", "afterOpening": "never"}],
        "react/jsx-uses-react": 2,
        "react/jsx-uses-vars": 2,
        "react/jsx-wrap-multilines": 2,
        "react/no-array-index-key": 0,
        "react/no-children-prop": 2,
        "react/no-danger": 2,
        "react/no-danger-with-children": 2,
        "react/no-deprecated": 0,
        "react/no-did-mount-set-state": 2,
        "react/no-did-update-set-state": 2,
        "react/no-direct-mutation-state": 2,
        "react/no-find-dome-node": 0,
        "react/no-is-mounted": 2,
        "react/no-multi-comp": 2,
        "react/no-redundant-should-component-update": 2,
        "react/no-render-return-value": 0,
        "react/no-set-state": 0,
        "react/no-string-refs": 2,
        "react/no-unescaped-entities": 2,
        "react/no-unknown-property": 2,
        "react/no-unused-prop-types": 0,
        "react/no-will-update-set-state": 2,
        "react/prefer-es6-class": 2,
        "react/prefer-stateless-function": [2, {"ignorePureComponents": true}],
        "react/prop-types": 2,
        "react/react-in-jsx-scope": 2,
        "react/require-default-props": 0,
        "react/require-optimization": 0,
        "react/require-render-return": 2,
        "react/self-closing-comp": 2,
        "react/sort-comp": 2,
        "react/sort-prop-types": [2, {"ignoreCase": true}],
        "react/style-prop-object": 2,
        "react/void-dom-elements-no-children": 2
    }
};
